lib/posthog/defaults.rb

Even though @fuziontech now made sure t.posthog.com works, I guess it makes sense to keep this consistent with other libs and use app.posthog.com?﻿

Update default host

---

CHANGELOG.md
lib/posthog/transport.rb
lib/posthog/worker.rb
spec/posthog/client_spec.rb
spec/posthog/transport_spec.rb

Use case: we have a staging environment with its own PostHog instance. It's not exposed to the internet, and uses a self-signed SSL certificate. This staging instance is useful for development. We currently need to manually change `transport.rb` to disable SSL verification, otherwise posthog-ruby's requests fail.
This PR makes it easier to use PostHog behind a self-signed SSL certificate by passing in an option to `PostHog::Client.new`. This will also allow us to send events from our staging Ruby app.
This is maybe a pretty niche requirement, so understandable if you don't want to merge it, but it'd be useful for us! I've tested these modifications with our Ruby app and it works.

Add ability to disable SSL verification

---

lib/posthog/client.rb

Hey guys! Just a headsup -- `present?` is not available outside of Rails. This causes client creation to fail with `undefined method .present? for nil::nilClass`.

present? is not available outside of Rails

---

lib/posthog/field_parser.rb
spec/posthog/client_spec.rb

Fixes https://github.com/PostHog/posthog-ruby/issues/13
We were rejecting calls for this before as distinct_id has been mandatory for some time.

Fix posthog.alias call

---

.gitignore
CHANGELOG.md
README.md
example.rb
lib/posthog/client.rb
lib/posthog/defaults.rb
lib/posthog/feature_flags.rb
lib/posthog/logging.rb
lib/posthog/send_worker.rb
lib/posthog/transport.rb
lib/posthog/utils.rb
posthog-ruby.gemspec
spec/posthog/client_spec.rb
spec/posthog/feature_flag_spec.rb
spec/posthog/utils_spec.rb
spec/spec_helper.rb

... and lots of accompanying fixes.
Follows spec from: https://github.com/PostHog/posthog/issues/10459#issuecomment-1193842228 , and is mostly a copy of https://github.com/PostHog/posthog-python/pull/68/files.
Also tagging @macobo for review, since I learned Ruby 2 days ago! (It _might_ look like a lot of code, but 3k is tests, 2k of which were generated from servers, and it felt easier to put everything in one PR, so we're sure we're not missing anything)
Start with the `changelog.md` to get a sense of changes, and then
some additional fixes to watch out for:
1. Cleans up the feature flag API requests we were making (it was very clunky, and `decide` requests weren't actually sending the payload, so this wasn't working at all)
2. Ensures that `send_feature_flags` on capture works, even …

Enable local evaluation of feature flags

---

posthog-ruby.gemspec

Remove concurrent gem limitation, it doesn't seem to have any deprecation warnings tied to it anymore?
https://github.com/PostHog/posthog-ruby/issues/24

Remove concurrent gem limitation

---

lib/posthog/client.rb
lib/posthog/feature_flags.rb
spec/posthog/client_spec.rb
spec/posthog/feature_flag_spec.rb

ruby fix for https://github.com/PostHog/posthog-python/pull/89

fix: capture call sends active feature flags only

---

lib/posthog/client.rb

Small change, found there is no mention about personal_api_key which forced me into reading gem code since it wasn't clear to me on how to pass it down (wasn't 100% sure that it actually handles it).

Add personal API key as option for Posthog::Client initializer

---

CHANGELOG.md
Gemfile
lib/posthog/feature_flags.rb
lib/posthog/version.rb
spec/posthog/feature_flag_spec.rb

ruby version of the relative date operator add and numeric ops fixes for local evaluation
https://github.com/PostHog/posthog-python/pull/105

feat(flags): add relative date operators and fix numeric ops

---

lib/posthog/client.rb
lib/posthog/feature_flags.rb
spec/posthog/client_spec.rb
spec/posthog/feature_flag_spec.rb

Copy of https://github.com/PostHog/posthog-python/pull/113

fix(flags): Update relative date op names

---

spec/posthog/send_worker_spec.rb
spec/spec_helper.rb

**Note**: This requires #41 and can be rebased once that is merged.
The tests were previously outputing a ton of stuff from the logger. I've silenced the logger. Additionally, I've fixed deprecation warnings.

Fix rspec output and warnings

---

lib/posthog/client.rb

The PostHog::Client calls Kernel#at_exit at each instantiation, which registers a process-global callback for each Client instance. This global callback is represented by a T_FILE entry in ObjectSpace.count_objects and is never GC'd for the life of the process.
Any process that instantiates multiple clients will be susceptible to this memory leak, which is very common in almost any long-running process, but in particular, the norm for Sidekiq / Resque environments. 
The good news is this line is completely unnecessary, since in the current implementation, the worker thread does not block the process from exiting, which means that setting this thread variable is unlikely to actually cause the thread to "gracefully exit" unless the code also blocked on Thread execution via Thread#join. In …

Fix memory leak in PostHog::Client.new

---

lib/posthog/client.rb
lib/posthog/defaults.rb
lib/posthog/feature_flags.rb
lib/posthog/field_parser.rb
posthog-ruby.gemspec
spec/posthog/client_spec.rb
spec/posthog/feature_flag_spec.rb

This PR does a few things:
1. Add a `feature_flag_request_timeout_seconds` configuration option, defaulting to 3s to control flag timeouts
2. Gets rid of a lot of error spew, instead allows passing in an on_error proc so users can decide what to do with errors
3. Unifies calling sites such that everything doesn't call the `/decide` endpoint directly, but via `get_all_flags_and_payloads` which in turn does all necessary error handling. Before this, getting payloads would always throw :/
4. Noticed as a result of above^ that we were sometimes inefficiently going to decide. The test updates where I add a second feature flag key for `beta-feature2` reflect that, since previously this would go to decide, but now it wouldn't, which is infact the ideal thing to do. (and thus to test the old flow …

fix(flags): Add appropriate timeouts, fix some other misc things

---

CHANGELOG.md
lib/posthog/feature_flags.rb
lib/posthog/version.rb
spec/posthog/feature_flag_spec.rb

with https://github.com/PostHog/posthog/pull/28564, we now start to respond different with the /decide and /local_evaluation APIs if users have gone over their quota limit. Now we need to change the SDKs to handle these new responses.

feat(feature-flags): support quota limiting for feature flags #85

---

lib/posthog/feature_flags.rb
lib/posthog/version.rb

I started noticing `posthog-ruby2.7.1: not found` in my logs after recently upgrading which I traced back to this line. In ruby \` invokes a shell command.

Remove rogue shell command

---

.github/workflows/unit-tests.yml
.vscode/.rspec
.vscode/settings.json
spec/posthog/feature_flag_spec.rb
spec/spec_helper.rb

This fixes a unit test that was failing due to sending the wrong header in the mocked request.
Other changes make developing on this project a little better. For example, Ruby LSP with Ruby Test Explorer was having issues because when it tries to discover tests and do a dry run, SimpleCov was trying to send results to the server. For whatever reason, the guards to ensure we were not in a dry run were not working. I changed it to check if we're in CI.
Also suppressed output in a test that was spewing out a lot of console output when running tests.

Fix failing test and some other local dev cleanup.

---

CHANGELOG.md
README.md
bin/helpers/_utils.sh
bin/test
lib/posthog/client.rb
lib/posthog/feature_flag.rb
lib/posthog/feature_flags.rb
lib/posthog/version.rb
spec/posthog/client_spec.rb
spec/posthog/decide_spec.rb
spec/posthog/feature_flag_spec.rb
spec/posthog/fixtures/test-decide-v3.json
spec/posthog/fixtures/test-decide-v4.json

Add support for `/decide?v=4` (see https://github.com/PostHog/posthog/pull/29751). Similar to how it's done in https://github.com/PostHog/posthog-js-lite/pull/427.
When capturing the `$feature_flag_called` event, additional information are now captured:
The end result is `$feature_flag_called` events will have additional properties:
| Property Name                |  Descirption
| ------------------------ | -------------
| `$feature_flag_version` | The version of the feature flag. This is visible in the diffs of the feature flag activity log.
| `$feature_flag_reason` | The reason the feature flag matched or didn't match.
| `$feature_flag_id`          | The database id of the feature flag (Just in case a flag was deleted and then recreated with the same key, we can determine the difference. …

chore(flags): Add request id, version, id, and reason to `$feature_flag_called` event

---

CHANGELOG.md
lib/posthog/feature_flag.rb
lib/posthog/feature_flags.rb
lib/posthog/version.rb
spec/posthog/client_spec.rb
spec/posthog/feature_flag_spec.rb
spec/posthog/flags_spec.rb

update Ruby SDK to use the new /flags endpoint instead of the legacy /decide one.

chore(flags): use new `/flags` endpoint instead of `/decide`

---

CHANGELOG.md
lib/posthog/client.rb
lib/posthog/version.rb
spec/posthog/client_spec.rb

and since I'm here let's add `before_send` to the lib...
would help with e.g. https://github.com/PostHog/posthog-ruby/issues/49

feat: add before_send function

---

CHANGELOG.md
lib/posthog/field_parser.rb
lib/posthog/version.rb
spec/posthog/client_spec.rb

made an example app to test https://github.com/PostHog/posthog.com/pull/11535
and saw that we were logging a warning when UUID was not provided and that's silly
don't do that

fix: was warning on absent UUID when capturing

---

.github/workflows/call-flags-project-board.yml

This ensures when an issue is assigned to the feature flags team or a member of the team is added as a reviewer to the PR, the PR is added to the flags project board.

chore: Add feature flags project board workflow

---

.env.example
.gitignore
EXAMPLE_SETUP.md
bin/fmt
bin/test
example.rb
lib/posthog/feature_flags.rb
spec/posthog/client_spec.rb
spec/posthog/feature_flag_spec.rb
spec/posthog/flags_spec.rb

Implements comprehensive cohort evaluation to enable full local evaluation of feature flags that depend on cohorts, bringing the Ruby SDK to feature parity with other server-side SDKs (Python, Node.js, Go, PHP, .NET).
Key changes:
- Add `send_cohorts` parameter to local evaluation requests
- Implement cohort storage and management in FeatureFlagsPoller
- Add `match_cohort()` and `match_property_group()` methods for cohort evaluation
- Support nested property groups with AND/OR logic
- Handle cohort-type properties in match_property()
- Update flag evaluation chain to pass cohort properties
- Add comprehensive test coverage for all cohort scenarios
- Update all test stubs to expect new URL format
This enables local evaluation of flags with cohorts, reducing API calls and improving …

feat: Add cohort evaluation support for local feature flag evaluation

---

lib/posthog/feature_flags.rb
spec/posthog/feature_flag_spec.rb

Feature flag condition sets with variant overrides were sorted to the top which was confusing and not how customers expected them to work.
https://github.com/PostHog/posthog/issues/37854
Remove sorting condition sets with variant overrides to the top to match server logic.

fix: don't sort condition sets with variant overrides to top
